### ISSUE TITLE
Does not seem to work with Python3?

### ISSUE THREAD

**Issue by danqing** [goshippo/shippo-python-client#24]
```
Collecting shippo==1.2.2 (from -r requirements.txt (line 38))
  Using cached shippo-1.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/z_/t4j3gq21121d0sj_wd4wqbn80000gn/T/pip-build-baoixqds/shippo/setup.py", line 5, in <module>
        from version import VERSION
    ImportError: No module named 'version'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/z_/t4j3gq21121d0sj_wd4wqbn80000gn/T/pip-build-baoixqds/shippo/
```

There also doesn't seem to be a Python3 binary on pypa.

**Comment by danqing** [comment]
Apparently there are a bunch of relative imports.

**Comment by mkaralek** [comment]
Same thing just happened to me.

**Comment by danqing** [comment]
#25 should fix it. Someone please accept the PR.

**Comment by danqing** [comment]
Thanks for merging @simonkreuz! If you can make a release that'd be awesome.

**Comment by mikhaill** [comment]
Thanks for the pull request, @danqing. We've pushed a new release.
